dev = false
warn_unknown_event_categorie = false

[log]
level = "info"
format = "text"
add_source = false

[server]
tracker_addr = ":8084"
public_tracker_url = "http://localhost:8084"
rewards_addr = ":8085"
public_rewards_url = "http://localhost:8085"
admin_password = "youshallnotpass"

[database]
host = "localhost" # replace with db in case you run with the compose.yml
port = 5432
username = "campfire-tools"
password = "password"
database = "campfire-tools"
ssl_mode = "disable"

[campfire_auth]
every = "2s"
burst = 10
max_retries = 3

[discord_auth]
client_id = "123456789012345678"
client_secret = "your_client_secret"
guild_id = "123456789012345678"
whitelist = ["123456789012345678"]
admins = ["123456789012345678"]

[notifications]
enabled = true
webhook_url = "https://discord.com/api/webhooks/<ID>/<TOKEN>"
